[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gibson042/canonicaljson-go"
  version = "1.0.3"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.0"

[[constraint]]
  name = "github.com/naoina/toml"
  version = "0.1.1"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"
